spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrdb?useSSL=true
    password: admin
    username:  root
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect:  org.hibernate.dialect.MySQLDialect
        id: 
          new_generator_mappings: false
        format_sql: true
  security:
    user:
      name: user
      password: thisispassword
      roles: ADMIN
  cache:
    type: NONE
