spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hrdb?useSSL=true
    password: admin
    username:  root
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQLDialect
        id: 
          new_generator_mappings: false
        format_sql: true
client:
  - username: user
    password: password
    roles: ADMIN, USER
  - usernam: user1
    password: password2
    roles: USER
    
